### ISSUE TITLE
[Bug]: Latest v1 release is broken

### ISSUE THREAD

**Issue by ghimire** [timo-reymann/deterministic-zip#20] opened 2023-06-19 14:15 UTC
### What happened?

The binary downloaded by installer script is not found in the latest `v1` release.

### OS

Ubuntu

### Problem description

The following link is generated by the installer script, which points to a binary file that does not exist.

```
curl -LsS https://github.com/timo-reymann/deterministic-zip/releases/download/v1/deterministic-zip_linux-amd64
```

Output:
Not Found

### Expected behaviour

Correct binary to be downloaded.

### Actual  behaviour

Link to binary is broken.

### Steps to Reproduce

```
curl -LsS https://github.com/timo-reymann/deterministic-zip/releases/download/v1/deterministic-zip_linux-amd64
```

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment] 2023-06-19 15:13
I messed up with tagging, that force push was intended for the GitHub action.

Fixed now and the installer should work out of the box without any changes since the latest release is now the official one.

**Closed by timo-reymann** 2023-06-19 15:13 UTC
Labels: bug
